apiVersion: v1
kind: ServiceAccount
metadata:
  name: mon-sa

---
kind: Pod
apiVersion: v1
metadata:
  name: Pod
  namespace: default
spec:
  containers:
    - name: test
      image: nginx:latest

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mon-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mon-binding
subjects:
- kind: ServiceAccount
  name: mon-sa
roleRef:
  kind: Role
  name: mon-role

---
